### ISSUE TITLE
reloadData create duplicate cell

### ISSUE THREAD

**Issue by MuhammadEhsanMirzaei** [iwheelbuy/SquareMosaicLayout#11]
Hi, when I use `collectionView.reloadData()` it cause to create duplicate cells on each other
![Screen Shot 2019-04-17 at 10 53 38 AM](https://user-images.githubusercontent.com/29886464/56266289-14014580-6101-11e9-98df-d7a0b66287f5.png)

**Comment by iwheelbuy** [comment]
well... any chance you share a sample project which reproduces this issue?

**Comment by MuhammadEhsanMirzaei** [comment]
`@IBAction func IncreaseRoomAction(_ sender: Any)
    {
            self.roomsModel.append(HotelPassengersModel())
            self.CollectionView_Rooms.reloadData()
    
    }
    
    @IBAction func DecreaseRoomAction(_ sender: Any)
    {
            self.roomsModel.removeLast()
            self.CollectionView_Rooms.reloadData()
        }
    }
    
    
    
    //MARK:- Functions
    
    //MARK:- Delegates
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 2 + self.roomsModel[section].Child.count
    }
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return roomsModel.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell: UICollectionViewCell = collectionView.dequeueCell(indexPath: indexPath)
        cell.contentView.backgroundColor = UIColor.clear
        cell.transform = CGAffineTransform(scaleX: -1, y: 1)
        let label = UILabel()
        label.text = "Cell \(indexPath.row)"
        label.font = UIFont.systemFont(ofSize: 20)
        label.textAlignment = .center
        label.frame = cell.contentView.bounds
        cell.contentView.addSubview(label)
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        switch kind {
        case SquareMosaicLayoutSectionBacker:
            let view: DecorationView = collectionView.dequeueSupplementary(kind, indexPath: indexPath, kind: kind)
            view.layer.backgroundColor = UIColor.clear.cgColor
            let subView = MDCCard()
            subView.translatesAutoresizingMaskIntoConstraints = false
            view.addSubview(subView)
            NSLayoutConstraint.activate([
                NSLayoutConstraint(item: subView, attribute: .right, relatedBy: .equal, toItem: view, attribute: .right, multiplier: 1.0, constant: -5.0),
                NSLayoutConstraint(item: subView, attribute: .left, relatedBy: .equal, toItem: view, attribute: .left, multiplier: 1.0, constant: 5.0),
                NSLayoutConstraint(item: subView, attribute: .top, relatedBy: .equal, toItem: view, attribute: .top, multiplier: 1.0, constant: 5.0),
                NSLayoutConstraint(item: subView, attribute: .bottom, relatedBy: .equal, toItem: view, attribute: .bottom, multiplier: 1.0, constant: 5.0)
                ])
            return view
        case SquareMosaicLayoutSectionHeader:
            let view: UICollectionReusableView = collectionView.dequeueSupplementary(kind, indexPath: indexPath, kind: kind)
            view.layer.backgroundColor = UIColor.clear.cgColor
            view.transform = CGAffineTransform(scaleX: -1, y: 1)
            let label = UILabel()
            label.text = "header"
            label.font = UIFont.systemFont(ofSize: 20)
            label.textAlignment = .center
            label.frame = view.bounds
            view.addSubview(label)
            
            return view
        default:
            fatalError()
        }
    }`

**Comment by iwheelbuy** [comment]
When you `dequeueSupplementary` you might get a new instance of supplementary if there is no already created. Or, you might get an old one (the dequeued one) which already have a subview. So, when you get an old one you manually add one more subview. It means it's your issue, not the issue of a layout.

I strongly advice you to read and investigate more information about tables/collections and its dequeue mechanism.
