### ISSUE TITLE
iOS 8 Support

### ISSUE THREAD

**Issue by ShivaHuang** [iwheelbuy/SquareMosaicLayout#4]
Hi, I'm wondering why the deploy target is iOS 9.0.
I tried the demo app on iOS 8.1 and it works quite normal.

Is there any other issue I didn't notice?

**Comment by iwheelbuy** [comment]
Hello. I have never thought about iOS 8 support. I usually make apps for two latest iOS version, that is the only reason. Do you need iOS 8 support?

**Comment by ShivaHuang** [comment]
Yeah, I need to support iOS 8. So I'm wondering if there any issue to make it only works above iOS 9.

If there should not be any problem, can you modify the pod spec and change the deploy target to iOS 8?

**Comment by iwheelbuy** [comment]
I've updated to version **0.6.1**. I don't have time to test it on iOS 8.0 atm so it's up to you.

**Comment by ShivaHuang** [comment]
Thank you. I'll try it and if I found anything wrong, I'll open a PR.
